server:
  port: 8889
security:
  user:
    name: ${SERVICE_BROKER_USERNAME:cloud-controller}
    password: ${SERVICE_BROKER_PASSWORD:foobar}
  ignored: /favicon.ico
  basic:
    enabled: false
#spring.datasource.url=jdbc:mysql://localhost/identity_service_broker
#spring.datasource.username=root
#spring.datasource.password
#spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring:
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
uaa:
  location: ${UAA_LOCATION:http://localhost:8080/uaa}
oauth2:
  client:
    tokenUri: ${uaa.location}/oauth/token
    authorizationUri: ${uaa.location}/oauth/authorize
    accessTokenUri: ${oauth2.client.tokenUri}
    clientId: oauth_showcase_authorization_code
    clientSecret: secret
  resource:
    tokenInfoUri: ${uaa.location}/check_token
    id: openid
    serviceId: ${PREFIX:}resource
    
oauth_clients:
  client_credentials:
    tokenUri: ${oauth2.client.tokenUri}
    authorizationUri: ${oauth2.client.authorizationUri}
    accessTokenUri: ${oauth2.client.tokenUri}
    clientId: oauth_showcase_client_credentials
    clientSecret: secret
  password_grant:
    tokenUri: ${oauth2.client.tokenUri}
    authorizationUri: ${oauth2.client.authorizationUri}
    accessTokenUri: ${oauth2.client.tokenUri}
    clientId: oauth_showcase_password_grant
    clientSecret: secret